RETRIEVAL_TOP_K = 10
SENTENCE_TRANSFORMER = "BAAI/bge-small-en-v1.5"
METADATA_FILTERING = False

RERANKER_TOP_K = 3
RERANKER_MODEL = "rerank-english-v3.0"

DB_NAME = "my_db"
TABLE_NAME = "financial_docs"

LANGCHAIN_PROJECT = "FINANCIAL_RAG"

CHAT_MODE = True
LLM_MODEL = "gpt-4o"